/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAnalyticsRouteImport } from './routes/_app/analytics'
import { Route as AppDoctorsRouteImport } from './routes/_app/doctors'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppDoctorsIndexRouteImport } from './routes/_app/doctors.index'
import { Route as AppDoctorsIdRouteImport } from './routes/_app/doctors.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppDoctorsRoute = AppDoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppDoctorsIndexRoute = AppDoctorsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppDoctorsRoute,
} as any)
const AppDoctorsIdRoute = AppDoctorsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppDoctorsRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/analytics': typeof AppAnalyticsRoute
  '/doctors': typeof AppDoctorsRouteWithChildren
  '/settings': typeof AppSettingsRoute
  '/doctors/$id': typeof AppDoctorsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/doctors/': typeof AppDoctorsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/analytics': typeof AppAnalyticsRoute
  '/settings': typeof AppSettingsRoute
  '/': typeof AppIndexRoute
  '/doctors/$id': typeof AppDoctorsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/doctors': typeof AppDoctorsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/doctors': typeof AppDoctorsRouteWithChildren
  '/_app/settings': typeof AppSettingsRoute
  '/_app/': typeof AppIndexRoute
  '/_app/doctors/$id': typeof AppDoctorsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_app/doctors/': typeof AppDoctorsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/analytics'
    | '/doctors'
    | '/settings'
    | '/doctors/$id'
    | '/api/auth/$'
    | '/doctors/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/analytics'
    | '/settings'
    | '/'
    | '/doctors/$id'
    | '/api/auth/$'
    | '/doctors'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/register'
    | '/_app/analytics'
    | '/_app/doctors'
    | '/_app/settings'
    | '/_app/'
    | '/_app/doctors/$id'
    | '/api/auth/$'
    | '/_app/doctors/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/doctors': {
      id: '/_app/doctors'
      path: '/doctors'
      fullPath: '/doctors'
      preLoaderRoute: typeof AppDoctorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/doctors/': {
      id: '/_app/doctors/'
      path: '/'
      fullPath: '/doctors/'
      preLoaderRoute: typeof AppDoctorsIndexRouteImport
      parentRoute: typeof AppDoctorsRoute
    }
    '/_app/doctors/$id': {
      id: '/_app/doctors/$id'
      path: '/$id'
      fullPath: '/doctors/$id'
      preLoaderRoute: typeof AppDoctorsIdRouteImport
      parentRoute: typeof AppDoctorsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppDoctorsRouteChildren {
  AppDoctorsIdRoute: typeof AppDoctorsIdRoute
  AppDoctorsIndexRoute: typeof AppDoctorsIndexRoute
}

const AppDoctorsRouteChildren: AppDoctorsRouteChildren = {
  AppDoctorsIdRoute: AppDoctorsIdRoute,
  AppDoctorsIndexRoute: AppDoctorsIndexRoute,
}

const AppDoctorsRouteWithChildren = AppDoctorsRoute._addFileChildren(
  AppDoctorsRouteChildren,
)

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppDoctorsRoute: typeof AppDoctorsRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppDoctorsRoute: AppDoctorsRouteWithChildren,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
